const arr = [
  "Android App Development Internship",
  "Angular.js Development Internship",
  "Backend Development Internship",
  "Bank Internship",
  "Big Data Internship",
  "Biotech Internship",
  "Biotechnology Internship",
  "Blockchain Development Internship",
  "Blogging Internship",
  "CAD Design Internship",
  "CS Articleship Internship",
  "Campus Ambassador Internship",
  "Client Servicing Internship",
  "Cloud Computing Internship",
  "Computer Science Internship",
  "Computer Vision Internship",
  "Cyber Security Internship",
  "Data Entry Internship",
  "Data Science Internship",
  "Database Building Internship",
  "Defence Internship",
  "Design Internship",
  "Embedded Systems Internship",
  "Energy Science And Engineering Internship",
  "Engineering Internship",
  "Flutter Development Internship",
  "Front End Development Internship",
  "Full Stack Development Internship",
  "Game Design Internship",
  "Game Development Internship",
  "Gaming Internship",
  "IT Internship",
  "Information Technology Internship",
  "Internet Of Things (IoT) Internship",
  "Java Internship",
  "Javascript Development Internship",
  "Machine Learning Internship",
  "Mobile App Development Internship",
  "Network Engineering Internship",
  "Networking Internship",
  "Node.js Development Internship",
  "PHP Development Internship",
  "Programming Internship",
  "Software Development Internship",
  "UI/UX Internship",
  "Web Development Internship",
  "Wordpress Development Internship",
  "IOS App Development Internship",
];
